### ISSUE TITLE
The Lambda service encountered an error: self signed certificate

### ISSUE THREAD

**Issue by HTPProXy** [rgraciano/echo-sonos#102] opened 2017-01-20 14:12 UTC
Hello,

I created a self signed certificate using openssl and set up echo-sonos to use the key and the cert file. I also set the both environment variables USE_HTTPS and REJECT_UNAUTHORIZED in the lambda management console.
But whenever I try to test I get this error:
The Lambda service encountered an error: self signed certificate

The certificate itself seems to work. Anyone else tried to activate SSL and got it working?

**Comment by rgraciano** [comment] 2017-01-23 05:12
@HTPProXy - just took a look at the options.js code, and it looks like that option will never work.  The way that options.js is written, some options will always be true :)  This regression was introduced whenever the env variables fix went in.  I'll put in a fix shortly and let you know

**Comment by rgraciano** [comment] 2017-01-23 05:41
@HTPProXy - this is fixed in 0703d7d.  If you update your options.js file, it should work now.  Previously, options.js would not let you set REJECT_UNAUTHORIZED to false, so it was impossible to use self-signed certs

**Closed by rgraciano** 2017-01-23 05:41 UTC

**Comment by HTPProXy** [comment] 2017-01-23 08:09
@rgraciano Thank you very much for the fix. Now it is working fine!
